### ISSUE TITLE
issue with installing fmeval

### ISSUE THREAD

**Issue by Erf-dev** [aws/fmeval#336]
I am trying to install fmeval, having Sagemaker, python 3.10, ml.m5.2xlarge, but I het the following error:

Collecting fmeval
  Using cached fmeval-1.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: IPython in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (8.28.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (3.10.10)
Collecting bert-score<0.4.0,>=0.3.13 (from fmeval)
  Using cached bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Collecting evaluate<0.5.0,>=0.4.0 (from fmeval)
  Using cached evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Collecting grpcio<2.0.0,>=1.60.0 (from fmeval)
  Using cached grpcio-1.68.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Requirement already satisfied: ipykernel<7.0.0,>=6.26.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (6.29.5)
Collecting jiwer<4.0.0,>=3.0.3 (from fmeval)
  Using cached jiwer-3.0.5-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: markdown in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (3.7)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (3.9.2)
Collecting mypy-boto3-bedrock<2.0.0,>=1.33.2 (from fmeval)
  Using cached mypy_boto3_bedrock-1.35.75-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: nltk<4.0.0,>=3.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (3.9.1)
Collecting pandas==2.1.4 (from fmeval)
  Using cached pandas-2.1.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: pyarrow in /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages (from fmeval) (17.0.0)
Collecting pyfunctional==1.4.3 (from fmeval)
  Using cached PyFunctional-1.4.3-py3-none-any.whl.metadata (24 kB)
Collecting ray==2.23.0 (from fmeval)
  Using cached ray-2.23.0-cp310-cp310-manylinux2014_x86_64.whl.metadata (13 kB)
Collecting rouge-score<0.2.0,>=0.1.2 (from fmeval)
  Using cached rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info
      writing /tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-olyj2bvy/rouge_score.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zs5yg5q_/rouge-score_29ca0893c3fa418480faf74b07d97508/setup.py", line 34, in <module>
          setuptools.setup(
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 545, in run
          self.prune_file_list()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
          super().prune_file_list()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Zhenshan-Jin** [comment]
Searching around on Google, for example, https://github.com/pypa/setuptools/issues/4483. This is not a issue specific to fmeval. 

Will close the issue for the moment.
